config/routes.rb
Rails.application.routes.draw do

    resources :restaurants, only: [ :index, :show, :new, :create ] do
      resources :reviews, only: [ :index, :new, :create ]
      end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :address, :phone_number, presence: true
  validates :name, uniqueness: true, presence: true
  validates :category, inclusion: { in: %w(belgian chinese french italian japanese medium large)}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    set_restaurant
    # @reviews = @restaurant.review
  end

  def new

    @restaurant = Restaurant.new

  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurants_path
  end


  def set_restaurant
     @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController


  def new
    set_restaurant
    @review = Review.new

  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = Restaurant.find(params[:restaurant_id])
    @review.save
    redirect_to restaurant_path(@review.restaurant)
  end

  def set_restaurant
     @restaurant = Restaurant.find(params[:restaurant_id])
  end

private

  def review_params
    params.require(:review).permit(:content, :restaurant_id, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/restaurants/index.html.erb
 <br>
<% @restaurants.each do |restaurant| %>

<%= restaurant.id %> --- <%= restaurant.name %><%= link_to "More details", restaurant_path(restaurant.id) %>
<br>

<% end %>
<br>
<br>
<%= link_to "Add a new resturant", new_restaurant_path %>

app/views/restaurants/new.html.erb
new restaurant
<br>
<br>

<%= simple_form_for (@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>
  <%= f.submit "add a restaurant", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/show.html.erb
show
<br>

<%= @restaurant.id %>
<%= @restaurant.name %>
<ul>
<li><%= @restaurant.address %></li>
<li><%= @restaurant.phone_number %></li>
<li><%= @restaurant.category %></li>
</ul>
<br>
<%= link_to 'list', restaurants_path %><br>

<%= link_to 'Add review', new_restaurant_review_path(@restaurant) %><br>
<h1>Reviews</h1>

<% @restaurant.reviews.each do |review| %>
  <%= review.rating %> --- <%= review.content %><br>
<% end %>

app/views/reviews/create.html.erb
<h1>review #create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/reviews/new.html.erb
new review
<br>
<br>

<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :rating %>
  <%= f.input :content %>

  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>